export const EXECUTION_TARGET_CAPABILITIES = [
  "browser-runtime",
  "native-runtime",
  "desktop-runtime",
  "service-runtime",
  "process-runtime",
  "external-runtime",
  "cold-start",
  "production-root",
  "pointer-input",
  "keyboard-input",
  "touch-input",
  "viewport-control",
  "pixel-density-observation",
  "safe-area-observation",
  "motion-observation",
  "reduced-motion",
  "color-scheme-control",
  "text-scale-control",
  "localization-control",
  "rtl-control",
  "assistive-technology",
  "screen-reader",
  "physical-device",
  "device-orientation",
  "sensor-input",
  "camera-input",
  "haptic-output",
  "audio-output",
  "reduced-transparency",
  "increased-contrast",
  "bold-text-control",
  "button-shapes-control",
  "system-ui-observation",
  "ime-control",
  "permission-control",
  "network-state-control",
  "lifecycle-control",
  "window-state-control",
  "fold-state-control",
  "thermal-observation",
  "power-mode-control",
  "persistent-storage",
  "network-boundary",
] as const;

export type ExecutionTargetCapabilityV2 =
  (typeof EXECUTION_TARGET_CAPABILITIES)[number];
