import { symbolicDeliveryRow as row } from "./symbolic_denotation_efficiency_delivery_catalog_row.mjs";

export const symbolicDeliveryItemsPart4 = [
  row(
    "independent-full-finite-test-expander",
    "technical_obligation",
    "architecture_ownership",
    "conformance_check",
    "verification",
    "Tests use an independently implemented full finite extensional expander and direct denotation comparator that does not call the production DAG canonicalizer or reuse its reduction logic.",
  ),
  row(
    "exhaustive-pointwise-equivalence-tests",
    "technical_obligation",
    "reliability_slo",
    "correctness",
    "verification",
    "Bounded exhaustive and property-generated tests compare V1 and V2 at every finite subject or relation, target, reachable condition or variation, applicable property and population or quantifier point for disposition, expected semantics and proof-obligation denotation.",
  ),
  row(
    "adversarial-false-completion-counterexamples",
    "technical_obligation",
    "fault_degradation_recovery",
    "fault_class",
    "verification",
    "Executable counterexamples independently remove or alter a condition, variation, property applicability region, relation endpoint, population quantifier, required method, expected locator, comparator, certificate edge or current result and must fail at the attributable identity.",
  ),
  row(
    "mixed-contract-verification",
    "technical_obligation",
    "compatibility_migration_rollout",
    "validation",
    "verification",
    "Tests compile and evidence one Contract containing at least one V1 target and one V2 target and reject cross-target binding, result and version confusion.",
  ),
  row(
    "capacity-early-rejection-verification",
    "technical_obligation",
    "performance_capacity_cost",
    "measurement_window",
    "verification",
    "Tests instrument read, parse, hydrate and expansion boundaries to prove oversized V1 inputs are rejected after stat or bounded prefix inspection and before full read, JSON parse, hydration or Cartesian work.",
  ),
  row(
    "complexity-parameter-verification",
    "technical_obligation",
    "performance_capacity_cost",
    "workload_model",
    "verification",
    "Parameter tests add irrelevant axes, values and dependency edges and assert exact denotation stability plus bounded obligation count, certificate coverage representation, canonical DAG nodes and bytes while theoretical ground cardinality grows.",
  ),
  row(
    "distribution-context-parity",
    "technical_obligation",
    "deployment_topology",
    "artifact_identity",
    "distribution",
    "Implementation, strict schemas, CLI, public types, package assets, managed workspace copies, README surfaces, PROJECT_SPEC, owning Context, implementation index, affected and Trust routing and focused tests must teach and enforce the same versioned semantics, scope and rollout.",
  ),
  row(
    "architecture-deliberation",
    "technical_obligation_architecture",
    "architecture_ownership",
    "selected_design",
    "architecture",
    "Architecture Deliberation: owners are design-resource handoff parsing and fact policy, the shared symbolic-denotation engine, Long-Task UI projection and evidence runtime, package distribution and owning Context; current extension points are V1 fact-manifest projection and Long-Task fact_expectations/fact_results. The selected design is a versioned opt-in UI V2 with restricted predicates, canonical shared DAGs, mutually exclusive regions, constant located expected values, complete package-policy plus Inspector-Census applicability, separately typed semantic and certificate obligations, V1 preparse capacity guards and mixed V1/V2 Final-Gate closure. Dependencies flow from canonical resources through handoff validation into Contract bindings and current evidence, never backward into value authority; state remains Contract and current-run owned and adds no lifecycle. Rejected alternatives are mutating V1, DNF or full expansion, post-expansion deduplication, arbitrary value functions, precedence, sampling, ungrounded N/A, historical proof reuse, non-UI bundling and Provider/P0 expansion. A future new predicate theory or non-UI consumer must extend the shared engine through a separately admitted domain policy without weakening canonical identity. Existing Cartesian memory risk is paid down through V1 early guards and V2 symbolic normalization; unrelated Provider debt is left out with an evidence re-entry condition. Project-owned equivalence, adversarial, capacity, mixed-version, distribution, complete-suite, Context and Final-Gate checks prove the declared design. Correctness, maintainability, compatibility, performance/capacity, reliability, operability and testability are triggered; security/privacy are preserved through strict grammar, bounded parsing and protected-value semantics.",
  ),
  row(
    "no-sampling",
    "forbidden_shortcut",
    "architecture_ownership",
    "forbidden_bypass",
    "safety",
    "Do not use representative, pairwise, random-only or risk-selected sampling to stand in for complete extensional denotation, applicability or final proof closure.",
  ),
  row(
    "no-granularity-reduction",
    "forbidden_shortcut",
    "architecture_ownership",
    "forbidden_bypass",
    "safety",
    "Do not reduce Fact, atomic property, condition, variation, relation, population, quantifier, required-method or observation-boundary granularity to obtain smaller artifacts.",
  ),
  row(
    "no-expand-then-deduplicate",
    "forbidden_shortcut",
    "architecture_ownership",
    "forbidden_bypass",
    "safety",
    "Do not first materialize the ground Cartesian universe and then group, hash, compress or deduplicate it; production complexity must be symbolic from input onward.",
  ),
  row(
    "no-historical-proof-reuse",
    "forbidden_shortcut",
    "architecture_ownership",
    "forbidden_bypass",
    "safety",
    "Do not reuse historical tests, receipts, Progress or a prior candidate's semantic or certificate results as current Final-Gate proof.",
  ),
  row(
    "no-authority-gate-proliferation",
    "forbidden_shortcut",
    "architecture_ownership",
    "forbidden_bypass",
    "safety",
    "Do not add a second Source, Contract, Authority, Final Gate, terminal theorem, registry, package completion state or acceptance workflow for symbolic or efficiency admission.",
  ),
  row(
    "no-arbitrary-symbolic-execution",
    "forbidden_shortcut",
    "architecture_ownership",
    "forbidden_bypass",
    "safety",
    "Do not admit arbitrary code, opaque predicates, implementation-owned expected-value functions or ordered override precedence into V2 Rules.",
  ),
  row(
    "no-ungrounded-applicability-omission",
    "forbidden_shortcut",
    "architecture_ownership",
    "forbidden_bypass",
    "safety",
    "Do not use a missing property, omitted axis, empty Census row, broad not-applicable label or provider complete flag as evidence-backed applicability closure.",
  ),
  row(
    "v1-v2-denotation-equivalence-ac",
    "acceptance",
    "goal_scope_glossary",
    "acceptance_meaning",
    "verification",
    "Given V1 and V2 representations of the same finite design universe, the independent expander observes set-equal pointwise disposition, expected semantics and proof-obligation denotation across every subject or relation, target, reachable condition or variation, applicable property and population or quantifier point; mutating any one component fails the exact comparison.",
    { acceptanceClaim: "requirement.complete-extensional-universe" },
  ),
  row(
    "canonical-region-and-applicability-ac",
    "acceptance",
    "goal_scope_glossary",
    "acceptance_meaning",
    "verification",
    "Given overlapping, gapped, redundant, reordered and Census-incomplete Rule inputs, valid equivalent inputs normalize to one digest while overlap, gap, unknown applicability, missing basis, unreachable claimed coverage and nonconstant expected values each fail closed.",
    { acceptanceClaim: "requirement.mutually-exclusive-effective-regions" },
  ),
  row(
    "mixed-contract-current-evidence-ac",
    "acceptance",
    "goal_scope_glossary",
    "acceptance_meaning",
    "verification",
    "Given one Contract with V1 and V2 targets, Compile preserves each representation's exact expectations and the existing Final Gate accepts only exact current V1 fact results, V2 Rule-method-region results and recomputed certificate results with no cross-target substitution.",
    { acceptanceClaim: "requirement.mixed-v1-v2-targets-one-contract" },
  ),
  row(
    "noninterference-complexity-ac",
    "acceptance",
    "goal_scope_glossary",
    "acceptance_meaning",
    "verification",
    "Given fixtures with increasing irrelevant axes, values and dependency edges, theoretical ground cardinality grows while denotation stays equal and obligation counts, exact set-valued certificate coverage, canonical DAG nodes and bytes remain within declared ground-independent budgets; adding a relevant dependency invalidates the certificate.",
    { acceptanceClaim: "requirement.complexity-independent-of-ground-cardinality" },
  ),
  row(
    "v1-capacity-guard-ac",
    "acceptance",
    "goal_scope_glossary",
    "acceptance_meaning",
    "verification",
    "Given V1 resources immediately below and above each byte, header and Fact Cell threshold, below-limit fixtures preserve V1 results and above-limit fixtures fail with measured diagnostics before prohibited full read, parse, hydration or Cartesian work; no row is truncated.",
    { acceptanceClaim: "requirement.v1-reject-before-hydration" },
  ),
  row(
    "scope-and-rollout-ac",
    "acceptance",
    "goal_scope_glossary",
    "acceptance_meaning",
    "verification",
    "Given legacy V1, explicit UI V2, non-UI semantic facts and Provider inputs, V1 remains default, UI V2 requires opt-in, mixed targets work, non-UI and Provider behavior remains unchanged and no later rollout step is treated as already authorized.",
    { acceptanceClaim: "requirement.ui-v2-explicit-opt-in" },
  ),
  row(
    "package-antidegradation-and-parity-ac",
    "acceptance",
    "goal_scope_glossary",
    "acceptance_meaning",
    "distribution",
    "Given the final candidate, focused equivalence, canonicalization, applicability, capacity, mixed-version, evidence, complexity and guidance tests plus the complete package suite, source parity, Context validation, Harness validation and sole Final Gate all pass from one committed snapshot without forbidden shortcuts or scope escape.",
    { acceptanceClaim: "requirement.complete-extensional-universe", complete: true },
  ),
  row(
    "inventory-is-not-completion",
    "non_completing",
    "goal_scope_glossary",
    "acceptance_meaning",
    "safety",
    "A complete Source, semantic manifest, symbolic DAG, certificate inventory, preflight, Compile, focused test, benchmark, Progress record or prose review alone does not complete delivery; only all declared checks rerun by the existing sole Final Gate on the current committed candidate can do so.",
  ),
  row(
    "public-schema-change-risk",
    "risk_fact",
    "architecture_ownership",
    "interface",
    "architecture",
    "This delivery adds versioned public UI handoff, Contract and evidence schema surfaces, so strict parser/schema/type parity, compatibility diagnostics, fixtures, documentation and package distribution must change together.",
    { riskFact: "public_api_or_schema_change" },
  ),
  row(
    "false-completion-critical-path-risk",
    "risk_fact",
    "reliability_slo",
    "correctness",
    "verification",
    "Symbolic omission is false-completion-critical because an overlap, gap, omitted dependency, narrowed applicability set or missing method can otherwise preserve aggregate green results while changing extensional meaning.",
    { riskFact: "critical_user_path" },
  ),
  row(
    "symbolic-oracle-observability-risk",
    "risk_fact",
    "reliability_slo",
    "measurement_point",
    "verification",
    "The Harness can prove declared canonicalization, denotation equality, certificate recomputation and current result closure, but semantic soundness of the frozen Inspector and independent test Oracle remains a named trusted-computing boundary requiring counterexamples and honest blocking.",
    { riskFact: "weak_observability" },
  ),];
