import { symbolicDeliveryRow as row } from "./symbolic_denotation_efficiency_delivery_catalog_row.mjs";

export const symbolicDeliveryItemsPart2 = [
  row(
    "exact-region-coverage-no-gaps",
    "requirement",
    "business_rule_calculation",
    "gap_handling",
    "symbolic-engine",
    "Canonical effective regions exactly partition every reachable applicable or explicitly disposed domain; any gap, duplicate coverage or unreachable claimed region fails with attributable identities.",
  ),
  row(
    "constant-located-expected-rule-values",
    "requirement",
    "data_model",
    "provenance",
    "symbolic-engine",
    "The first V2 Rule representation permits only one constant located expected value per effective Rule region; the value locator and digest are canonical-resource authority.",
  ),
  row(
    "no-rule-precedence-or-value-function",
    "technical_obligation",
    "architecture_ownership",
    "rejected_alternative",
    "symbolic-engine",
    "The first V2 rejects ordered override precedence, computed expected-value functions, arbitrary code and late implementation-owned value resolution because they weaken canonical mutual exclusion and equivalence proof.",
  ),
  row(
    "deterministic-canonical-identity",
    "technical_obligation",
    "data_model",
    "identity",
    "symbolic-engine",
    "Equivalent symbolic inputs normalize to the same canonical DAG serialization and digest independent of declaration ordering, redundant predicates or chunk boundaries.",
  ),
  row(
    "symbolic-complexity-fuse",
    "technical_obligation",
    "performance_capacity_cost",
    "resource_budget",
    "symbolic-engine",
    "Fail-closed complexity fuses bound predicate depth, input predicate nodes, canonical DAG nodes, partition edges and canonical bytes; exhaustion reports unavailable and never samples or truncates.",
  ),
  row(
    "ground-cardinality-diagnostic-only",
    "technical_obligation",
    "observability",
    "metric",
    "symbolic-engine",
    "Theoretical ground cardinality is computed with overflow-safe integer arithmetic for diagnostics and admission comparisons only; it is never used to allocate or iterate a ground array in production.",
  ),
  row(
    "package-policy-property-catalog",
    "requirement",
    "data_model",
    "schema",
    "applicability",
    "Property applicability starts from the complete package-owned standard property catalog plus validated custom properties; the Inspector cannot silently narrow that candidate catalog.",
  ),
  row(
    "inspector-census-applicability",
    "requirement",
    "architecture_ownership",
    "input_boundary",
    "applicability",
    "Every property region reported applicable must be supported by the frozen Inspector Census, capability declaration, inspected input closure and exact subject or relation identity.",
  ),
  row(
    "basis-backed-property-remainder",
    "requirement",
    "business_rule_calculation",
    "exception",
    "applicability",
    "For every package-catalog property not applicable in a reachable region, the complete remainder is covered by an exact basis-backed not-applicable, excluded, decision-required or unavailable disposition.",
  ),
  row(
    "unknown-applicability-blocks",
    "requirement",
    "fault_degradation_recovery",
    "detection",
    "applicability",
    "Unknown Inspector capability, unreadable input, unresolved custom property, incomplete Census or uncovered applicability remainder blocks ready rather than defaulting to not-applicable.",
  ),
  row(
    "relation-population-first-class-model",
    "technical_obligation",
    "data_model",
    "cardinality",
    "applicability",
    "Symbolic Fact Rules model local subjects, typed relations, static populations and dynamic populations directly; relation endpoints or population members cannot be hidden in labels.",
  ),
  row(
    "population-quantifier-denotation",
    "technical_obligation",
    "data_model",
    "absence_semantics",
    "applicability",
    "Each Rule and semantic obligation preserves exact one, all, any, none, exactly, at-least, at-most or range quantifier meaning and its population reference.",
  ),
  row(
    "v2-rule-method-region-projection",
    "technical_obligation",
    "operation_workflow",
    "output",
    "downstream",
    "For an opted-in V2 target, Long-Task compilation projects each semantic Fact Rule to every required method and only the necessary canonical method region, without reconstructing V1 ground rows.",
  ),
  row(
    "stable-symbolic-fact-rule-identity",
    "technical_obligation",
    "data_model",
    "identity",
    "downstream",
    "V2 Fact Rule identities are stable under canonical-equivalent predicate rewrites while semantic proof obligations and certificate obligations retain distinct identities.",
  ),
  row(
    "per-method-region-obligations",
    "technical_obligation",
    "operation_workflow",
    "postcondition",
    "downstream",
    "Every property-required method receives an independently attributable semantic obligation over its exact canonical region, comparator, Oracle, environment and observation boundary.",
  ),
  row(
    "typed-v2-rule-results",
    "technical_obligation",
    "output_error",
    "schema",
    "downstream",
    "Current-candidate V2 evidence contains typed per-Rule and per-method-region results with attributable actual observation, comparison, verdict, Oracle, environment and protected-value policy.",
  ),
  row(
    "typed-certificate-results",
    "technical_obligation",
    "output_error",
    "schema",
    "downstream",
    "Current-candidate V2 evidence contains typed separately evaluated non-interference certificate results; a certificate declaration without a fresh recomputed result proves nothing.",
  ),
  row(
    "current-snapshot-evidence-only",
    "requirement",
    "reliability_slo",
    "freshness",
    "downstream",
    "All V1 and V2 semantic and certificate results are produced from the same current final candidate after the last controlling-input change; Progress, receipts and historical passing results are non-authoritative.",
  ),
  row(
    "mixed-target-one-final-gate",
    "technical_obligation",
    "compatibility_migration_rollout",
    "mixed_version",
    "downstream",
    "The existing Long-Task Final Gate evaluates mixed V1 and V2 target expectations together and remains the sole current-snapshot acceptance carrier.",
  ),
  row(
    "set-valued-noninterference-certificates",
    "requirement",
    "architecture_ownership",
    "interface",
    "noninterference",
    "One set-valued non-interference certificate may cover multiple Rule identities, omitted axes and dependency edges when the package independently proves that exact covered set.",
  ),
  row(
    "certificate-omitted-axis-coverage",
    "requirement",
    "observability",
    "dimension",
    "noninterference",
    "Non-interference accounting reports the exact set and count of omitted axes covered by each certificate and rejects unknown, reachable-but-uncovered or semantically relevant omissions.",
  ),
  row(
    "certificate-dependency-edge-coverage",
    "requirement",
    "observability",
    "causation",
    "noninterference",
    "Non-interference accounting reports the exact set and count of dependency edges covered by each certificate and rejects an omitted edge that can affect disposition, expected semantics or proof denotation.",
  ),
  row(
    "noninterference-obligation-count-metric",
    "requirement",
    "performance_capacity_cost",
    "workload_model",
    "noninterference",
    "Admission and regression evidence reports semantic obligation count and certificate obligation count separately.",
  ),
  row(
    "noninterference-dag-node-count-metric",
    "requirement",
    "performance_capacity_cost",
    "dataset_cardinality",
    "noninterference",
    "Admission and regression evidence reports canonical DAG node and partition-edge counts for each fixture.",
  ),
  row(
    "noninterference-byte-count-metric",
    "requirement",
    "performance_capacity_cost",
    "payload",
    "noninterference",
    "Admission and regression evidence reports canonical serialized bytes and relevant Contract and evidence bytes for each fixture.",
  ),
  row(
    "complexity-independent-of-ground-cardinality",
    "requirement",
    "performance_capacity_cost",
    "scaling",
    "noninterference",
    "For fixtures that add semantically irrelevant axes or domain values while holding the reduced function and declared certificate sets constant, obligations, certificate coverage representation, canonical DAG nodes and bytes must remain bounded independently of theoretical ground cardinality.",
  ),
  row(
    "certificate-package-recomputation",
    "technical_obligation",
    "compatibility_migration_rollout",
    "validation",
    "noninterference",
    "The package recomputes certificate coverage, variable dependence, region equivalence and canonical identities from frozen symbolic inputs; provider or author complete booleans are not trusted.",
  ),
  row(
    "certificate-not-semantic-proof-substitute",
    "technical_obligation",
    "architecture_ownership",
    "forbidden_bypass",
    "noninterference",
    "Non-interference certificates prove only safe representation omission and sharing; they do not replace pointwise semantic Facts, required-method denotation or current production observations.",
  ),
  row(
    "no-obligation-per-irrelevant-axis-rule",
    "requirement",
    "performance_capacity_cost",
    "cost_boundary",
    "noninterference",
    "The model does not mechanically add one semantic or certificate obligation for every newly introduced irrelevant axis when one exact set-valued certificate already covers the changed omission set.",
  ),
];
