import { symbolicDeliveryRow as row } from "./symbolic_denotation_efficiency_delivery_catalog_row.mjs";

export const symbolicDeliveryItemsPart3 = [
  row(
    "v1-stat-before-read",
    "technical_obligation",
    "performance_capacity_cost",
    "resource_budget",
    "capacity",
    "V1 handoff and manifest resources are stat-checked against declared byte budgets before any whole-file read, YAML or JSON parse, hydration or Cartesian validation.",
  ),
  row(
    "v1-bounded-prefix-stream-parse",
    "technical_obligation",
    "input_validation",
    "size_limit",
    "capacity",
    "Compact V1 manifest admission reads at most the declared bounded prefix to obtain schema version and generation collection counts before whole-file parsing; a missing or late capacity header fails with actionable guidance.",
  ),
  row(
    "v1-capacity-header-order",
    "technical_obligation",
    "api_protocol",
    "serialization",
    "capacity",
    "V1 canonical manifest serialization places schema identity and generation collection count metadata before large collections so the bounded preparse is deterministic and does not scan the full document.",
  ),
  row(
    "v1-embedded-handoff-byte-limit",
    "technical_obligation",
    "performance_capacity_cost",
    "payload",
    "capacity",
    "The embedded V1 handoff hard limit is 8,388,608 bytes, derived as the next power of two above four times the measured 1,930,720-byte complete reference fixture.",
  ),
  row(
    "v1-manifest-byte-limit",
    "technical_obligation",
    "performance_capacity_cost",
    "payload",
    "capacity",
    "The compact V1 canonical manifest hard limit is 33,554,432 bytes, derived as the next power of two above four times the measured 4,411,120-byte complete reference fixture.",
  ),
  row(
    "v1-ground-cell-limit",
    "technical_obligation",
    "performance_capacity_cost",
    "dataset_cardinality",
    "capacity",
    "The V1 explicit expected Fact Cell hard limit is 16,384, derived as the next power of two above four times the measured 3,038-cell complete reference fixture; V2 regeneration is the required path above it.",
  ),
  row(
    "v1-capacity-prefix-limit",
    "technical_obligation",
    "performance_capacity_cost",
    "resource_budget",
    "capacity",
    "The capacity-header streaming prefix is bounded to 65,536 bytes and admission rejects a manifest whose required header is not wholly available within that schema budget.",
  ),
  row(
    "v1-reject-before-hydration",
    "requirement",
    "fault_degradation_recovery",
    "detection",
    "capacity",
    "A V1 size or expected-count violation is rejected before JSON parsing, manifest projection, condition or variation expansion and handoff hydration, with no partial acceptance.",
  ),
  row(
    "v1-threshold-measurement-basis",
    "technical_obligation",
    "performance_capacity_cost",
    "benchmark_environment",
    "capacity",
    "Threshold evidence is the current repository complete fixture on Windows x64, Node 24.16.0 and an Intel i5-11400F: 33 condition axes, 30 variation-axis rows, 2 conditions, 6 subjects, 7 variations, 217 properties, 3,038 Fact Cells, 36 Facts and 48 proof obligations; embedded handoff 1,930,720 bytes, compact handoff 113,792 bytes and canonical manifest 4,411,120 bytes.",
  ),
  row(
    "v1-capacity-actionable-diagnostics",
    "technical_obligation",
    "observability",
    "runbook_mitigation",
    "capacity",
    "Capacity rejection reports measured bytes, declared counts, limit, the largest available contributors and the exact opt-in V2 regeneration route without logging protected expected values.",
  ),
  row(
    "capacity-fail-closed-no-truncation",
    "requirement",
    "fault_degradation_recovery",
    "degraded_result",
    "capacity",
    "Capacity protection never truncates, samples, summarizes, lowers granularity or silently falls back to a partial V1 universe; exceeding a budget is unavailable until the producer regenerates an admitted V2 representation.",
  ),
  row(
    "efficiency-admission-property-only",
    "requirement",
    "architecture_ownership",
    "lifecycle_boundary",
    "efficiency",
    "Purpose-fulfillment efficiency non-degradation is a package mechanism-change admission and regression property evaluated before adopting or defaulting the mechanism.",
  ),
  row(
    "efficiency-not-terminal-safety-theorem",
    "requirement",
    "goal_scope_glossary",
    "non_goal",
    "efficiency",
    "Purpose-fulfillment efficiency non-degradation is not part of the AcceptedDeliveryTerminal safety theorem and cannot become a delivery-completion condition.",
  ),
  row(
    "no-second-authority",
    "technical_obligation",
    "architecture_ownership",
    "owner",
    "efficiency",
    "Efficiency admission creates no second Source, Contract Authority, value authority or acceptance authority.",
  ),
  row(
    "no-second-final-gate",
    "technical_obligation",
    "architecture_ownership",
    "lifecycle_boundary",
    "efficiency",
    "Efficiency admission creates no second Final Gate, package completion state or alternate machine-acceptance terminal.",
  ),
  row(
    "no-delivery-deadline-condition",
    "requirement",
    "goal_scope_glossary",
    "non_goal",
    "efficiency",
    "The mechanism introduces no delivery deadline, elapsed-time acceptance predicate or fixed completion-time promise.",
  ),
  row(
    "no-fixed-execution-flow",
    "requirement",
    "goal_scope_glossary",
    "non_goal",
    "efficiency",
    "The mechanism introduces no fixed implementation order, per-edit mandate, scheduler, agent-allocation rule or workflow phase beyond the existing Goal-owned freedom boundary.",
  ),
  row(
    "performance-claim-measurement-contract",
    "technical_obligation",
    "performance_capacity_cost",
    "statistical_method",
    "efficiency",
    "Any runtime efficiency claim must name workload, metric, baseline or budget, environment, comparator and tolerance and must be produced by a project-owned current-candidate measurement; static representation shape alone is not runtime proof.",
  ),
  row(
    "non-ui-v2-separate-admission",
    "requirement",
    "compatibility_migration_rollout",
    "phased_rollout",
    "scope",
    "Non-UI semantic-fact V2 is outside this delivery and requires a separate admission after UI V2 proves the shared engine boundary; existing semantic-fact-manifest-v1 behavior is unchanged here.",
  ),
  row(
    "provider-p0-excluded",
    "requirement",
    "external_integration",
    "external_confirmation",
    "scope",
    "Provider trust-boundary and P0 acquisition changes are outside this delivery because no repository-reproducible failure evidence currently justifies them.",
  ),
  row(
    "provider-reentry-evidence-required",
    "requirement",
    "external_integration",
    "side_effect_observation",
    "scope",
    "Provider or P0 scope may re-enter only through a separately reviewed repository-reproducible failing fixture, exact ownership analysis and Authority revision or new delivery.",
  ),
  row(
    "shared-engine-future-boundary",
    "technical_obligation",
    "architecture_ownership",
    "extension_point",
    "scope",
    "The symbolic predicate and canonical DAG engine is domain-neutral and package-owned, but UI schema, applicability policy and Contract projection remain UI-owned so a future non-UI admission can reuse the engine without importing UI semantics.",
  ),
  row(
    "rollout-1-v1-capacity",
    "requirement",
    "compatibility_migration_rollout",
    "phased_rollout",
    "rollout",
    "Rollout step 1 ships and verifies V1 stat and bounded-stream capacity protection before any V2 default behavior.",
  ),
  row(
    "rollout-2-formal-denotation",
    "requirement",
    "compatibility_migration_rollout",
    "phased_rollout",
    "rollout",
    "Rollout step 2 freezes the formal V1/V2 extensional denotation and equivalence predicates before production symbolic projection is accepted.",
  ),
  row(
    "rollout-3-engine-independent-oracle",
    "requirement",
    "compatibility_migration_rollout",
    "phased_rollout",
    "rollout",
    "Rollout step 3 implements the internal symbolic engine together with an independently authored test-only full finite expander and comparator Oracle.",
  ),
  row(
    "rollout-4-ui-v2-opt-in",
    "requirement",
    "compatibility_migration_rollout",
    "phased_rollout",
    "rollout",
    "Rollout step 4 admits UI V2 only as explicit opt-in after equivalence and complexity counterexamples pass.",
  ),
  row(
    "rollout-5-mixed-downstream",
    "requirement",
    "compatibility_migration_rollout",
    "phased_rollout",
    "rollout",
    "Rollout step 5 admits mixed V1 and V2 downstream Contract and evidence closure in the same Final Gate.",
  ),
  row(
    "rollout-6-default-after-proof",
    "requirement",
    "compatibility_migration_rollout",
    "phased_rollout",
    "rollout",
    "Rollout step 6 may change the UI default only in a later Authority-backed decision after equivalence, compatibility, false-negative resistance and measured efficiency admission remain passing; this delivery does not flip the default.",
  ),
  row(
    "rollout-7-non-ui-provider-separate",
    "requirement",
    "compatibility_migration_rollout",
    "phased_rollout",
    "rollout",
    "Rollout step 7 treats non-UI V2 and any Provider trust-boundary work as separate admissions with their own evidence rather than implied follow-through.",
  ),
];
